### PR TITLE
Rewrote the cli

### PR DESCRIPTION
**Pull request by Pranjal-Patel**

### CODE REVIEW

**Comment by 0x454d505459** [comment]
I just compiled your fork with the changes, why is everything under usage section (included) indented a lot ?

When specifying the debug flag before the file it errors "File -d doesn't exits", same for --run.

**Review by MrinmoyHaloi — CHANGES_REQUESTED** [review]
.

**Comment by Pranjal-Patel** [comment]
I made the required changes

**Comment by Pranjal-Patel** [comment]
fixed the cmake file too

**Review by In-diaonic — APPROVED** [review]

**Review by In-diaonic — CHANGES_REQUESTED** [review]
I see you have used `pragma` in the cli header, please do not use a feature which isn't defined in the C++ standard.

**Comment by Pranjal-Patel** [comment]
That isn't a problem at all, but I'll remove that

**Comment by Pranjal-Patel** [comment]
done

**Review by MrinmoyHaloi — APPROVED** [review]

**Pull request merged**
